### ISSUE TITLE
我这边有段比较大的js执行出错

### ISSUE THREAD

**Issue by zoulux** [Ahaochan/js_deobfuscation#1]
你好 朋友，今天翻阅 github 恰好看到您的项目，我这边有个 10mb 的 js 需要进行反混淆正好试了一下，现在根据您的脚本，现在会随机产生两个错误，

##其一

```js
/Users/jake/tmp/js_deobfuscation/node_modules/@babel/parser/lib/index.js:3258
    if (!this.options.errorRecovery) throw error;
                                     ^

SyntaxError: Unexpected token (3:21)
    at instantiate (/Users/jake/tmp/js_deobfuscation/node_modules/@babel/parser/lib/index.js:64:32)
    at constructor (/Users/jake/tmp/js_deobfuscation/node_modules/@babel/parser/lib/index.js:362:12)
    at Parser.raise (/Users/jake/tmp/js_deobfuscation/node_modules/@babel/parser/lib/index.js:3254:19)
    at Parser.unexpected (/Users/jake/tmp/js_deobfuscation/node_modules/@babel/parser/lib/index.js:3284:16)
    at Parser.parseExprAtom (/Users/jake/tmp/js_deobfuscation/node_modules/@babel/parser/lib/index.js:11231:22)
    at Parser.parseExprSubscripts (/Users/jake/tmp/js_deobfuscation/node_modules/@babel/parser/lib/index.js:10847:23)
    at Parser.parseUpdate (/Users/jake/tmp/js_deobfuscation/node_modules/@babel/parser/lib/index.js:10830:21)
    at Parser.parseMaybeUnary (/Users/jake/tmp/js_deobfuscation/node_modules/@babel/parser/lib/index.js:10806:23)
    at Parser.parseMaybeUnaryOrPrivate (/Users/jake/tmp/js_deobfuscation/node_modules/@babel/parser/lib/index.js:10644:61)
    at Parser.parseExprOps (/Users/jake/tmp/js_deobfuscation/node_modules/@babel/parser/lib/index.js:10649:23) {
  code: 'BABEL_PARSER_SYNTAX_ERROR',
  reasonCode: 'UnexpectedToken',
  loc: Position { line: 3, column: 21, index: 43 },
  pos: [Getter/Setter]
}

Node.js v19.6.0

```

##其二

```js
预处理完毕
/Users/jake/tmp/js_deobfuscation/node_modules/@babel/traverse/lib/path/family.js:232
function get(key, context = true) {
            ^

RangeError: Maximum call stack size exceeded
    at NodePath.get (/Users/jake/tmp/js_deobfuscation/node_modules/@babel/traverse/lib/path/family.js:232:13)
    at _evaluate (/Users/jake/tmp/js_deobfuscation/node_modules/@babel/traverse/lib/path/evaluation.js:144:27)
    at evaluateCached (/Users/jake/tmp/js_deobfuscation/node_modules/@babel/traverse/lib/path/evaluation.js:45:17)
    at NodePath.evaluate (/Users/jake/tmp/js_deobfuscation/node_modules/@babel/traverse/lib/path/evaluation.js:325:15)
    at UnaryExpression|BinaryExpression|CallExpression|ConditionalExpression (/Users/jake/tmp/js_deobfuscation/utils.js:313:49)
    at NodePath._call (/Users/jake/tmp/js_deobfuscation/node_modules/@babel/traverse/lib/path/context.js:45:20)
    at NodePath.call (/Users/jake/tmp/js_deobfuscation/node_modules/@babel/traverse/lib/path/context.js:35:17)
    at NodePath.visit (/Users/jake/tmp/js_deobfuscation/node_modules/@babel/traverse/lib/path/context.js:80:31)
    at TraversalContext.visitQueue (/Users/jake/tmp/js_deobfuscation/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitQueue (/Users/jake/tmp/js_deobfuscation/node_modules/@babel/traverse/lib/context.js:91:21)

Node.js v19.6.0
```

**Comment by renjie9527** [comment]
解决了吗 我和你第二个错误一样
